# Page settings
baseurl = "http://marvelloussoft.github.io/marvinc"
title = "Careers at Marvellous"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]

  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "MarvellousSoft"
  description = "MarvInc is a zachlike puzzle game with a story told through emails."
  email = "marvellous.amoeba@gmail.com"
  # Navigation
  [params.navigation]
    brand = "Marvellous Inc."
    home = "Home"
    services = "Work and Benefits"
    testimonials = "Testimonials"
    work = "Teams"
    about = "Students"
    contact = "Apply now"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

  # Hero section
  [params.hero]
    logo = '<img height="200" src="images/logo.png">'
    title = "Building a better tomorrow."
    post_title = "**Right now.**"
    subtitle = ""

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Our Objectives"
    description = "People are at the heart of Marvellous. We seek to design products that help connect people all around the world, inspiring millions to make the world a better place."
    icon = "icon-trophy"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Our Values"
    description = "We want to make a difference. To change the world and bring the world closer together. We value diversity, innovation, creativity and adventurousness."
    icon = "icon-star"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Our Family"
    description = "Here at Marvellous, working with us means you're part of our family. And family takes care of each other. All of our employees are entitled to benefits and perks."
    icon = "icon-home"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"


  # Services section
  [params.services]
    enable = true
    weight = 100
    title = "Work and Benefits"
    description = "Working at Marvellous Inc. means being part of the MarvFamily, and just like family, we're always concerned about your wellbeing. Here are some of the perks of being part of our Family!"

    [[params.services.item]]
      title = "Health"
      description = "As a leading innovator in Medical Research, Marvellous knows that health is important. Benefits like great dental plan, a free all-covering health care, and maternity and paternity leave means a healthy family. For yourself and your loved ones."
      icon = "icon-heart"

    [[params.services.item]]
      title = "Family"
      description = "Since we know family matters the most, taking care of your family is a priority for us. Be them medical appointments, a long ago planned vacation or even just taking your kid to soccer practice, the MarvFamily has got you covered!"
      icon = "icon-people"

    [[params.services.item]]
      title = "Legal Team"
      description = "Part of the Family means helping you, whatever it may be. And for that, our legal team is ready to assist you in any civil case, as long it doesn't compromise the company. After all, you don't want to hurt family, do you?"
      icon = "icon-shield"

      [[params.services.item]]
      title = "Opportunity"
      description = "We give you the chance to change the world in a meaninful way. It doesn't matter whether you are joining us as a lawyer or a Molecular Biologist. We at Marvellous Inc. are all walking hand in hand towards the same goal: to make a better tomorrow; right now."
      icon = "icon-chemistry"


  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "Marvellous is home to many amazing minds from all around the world. Read what some of our most successful researchers have to say about working at Marvellous Inc.!"
    footertext = 'The views expressed by the employees of Marvellous Inc. do not reflect the views of the company. The above testimonials may have been altered to protect company IP and/or classified documents, and may not be the exact quotes by their authors.'

    [[params.testimonials.item]]
      quote = "&ldquo;It's a great place. We get to do state of the art research that is going to make the world a better place. Plus, MarvInc is a very liberal company, and I get to [...] help people. I love [...] MarvInc.&rdquo;"
      person = 'Paul Verkeufen <span class="subtext">Head Engineer at Material Engineering Dept.</span>'

    [[params.testimonials.item]]
      quote = "&ldquo;Last weekend we had a hackaton at the company. 48 hours straight coding some new system, it was pretty great. Specially since we [...] were very productive.&rdquo;"
      person = 'Olivia Kavanagh <span class="subtext">Head Engineer at Software Development Dept.</span>'

    [[params.testimonials.item]]
      quote = "&ldquo;&rdquo;"
      person = 'Janine Leubwitz <span class="subtext">Head Engineer at Robot Testing Dept.</span>'

  # Work section
  [params.work]
    enable = true
    title = "Teams"
    description = "Learn more about the many departments at Marvellous Inc.! Choose what fits you best and be yet another member of our Family!"

    [[params.work.row]]
      img = "biomed.png"
      alt = "Biology and Medical Branch (BMB)"
      title = "Biology and Medical Branch (BMB)"
      subtitle = "The Biology and Medical Branch is the best choice for researchers with PhDs in Molecular Biology, Epidemiology, Neuroscience and more!"

    [[params.work.row]]
      img = "materials.png"
      alt = "Fluids and Materials Branch (FMB)"
      title = "Fluids and Materials Branch (FMB)"
      subtitle = "Join the best engineers, physics and chemists at the FMB! Research on Fluid Mechanics and Materials Science."

    [[params.work.row]]
      img = "math.png"
      alt = "Mathematics and Statistics Branch (MSB)"
      title = "Mathematics and Statistics Branch (MSB)"
      subtitle = "Innovative research on the fields of Cryptography, Probabilistic Models, Machine Learning and Number Theory." 

    [[params.work.row]]
      img = "legal.png"
      alt = "Legal Team (LT)"
      title = "Legal Team"
      subtitle = "Be part of our legal team, helping us protect our Family and the company! Join the Legal Team now!"

    [[params.work.row]]
      img = "marketing.png"
      alt = "Marketing Team (MT)"
      title = "Marketing Team"
      subtitle = "Our marketing team employs the most creative minds to help spread the Marvellous Word! We seek graduates in Product and Brand Marketing."

    [[params.work.row]]
      img = "software.png"
      alt = "Software and Microcoding Branch (SMB)"
      title = "Software and Microcoding Branch (SMB)"
      subtitle = "The SMB are the coders of Marvellous, working with various other Branches and Teams. Jobs for our SMBers depend on their aptitude and interests."

    [[params.work.row]]
      img = "electric.png"
      alt = "Electric and Electronic Branch (EEB)"
      title = "Electric and Electronic Branch (EEB)"
      subtitle = "At the EEB, state-of-the-art research on Nanotechnology, Circuit Miniturization, and Energy Distribution and Storage is done everyday by our best engineers and physics."

    [[params.work.row]]
      img = "space.png"
      alt = "Space and Interplanetary Branch (SIB)"
      title = "Space and Interplanetary Branch (SIB)"
      subtitle = "Our Space and Interplanetary Branch are working hard to make interplanetary travel an everyday thing."

    [[params.work.row]]
      img = "robot.png"
      alt = "Robotics Branch (RB)"
      title = "Robotics Branch (RB)"
      subtitle = "The Robotics Branch works closely with all other Science Branches to bring you exciting new products that will revolutionize the world!" 

  # About section
  [params.about]
    enable = true
    title = "Students"
    description = '''
Marvellous Inc. is always looking for creative and innovative minds, whatever their age may be. We grant full and partial scholarships to prominent young adults in STEM in the US, Europe and developing countries.

<img height="150" src="images/students1.png">
<img height="150" src="images/students2.png">
<img height="150" src="images/students3.png">

If you're in College and interested in working with us, we also have open positions for undergraduate and graduate internships.

<img height="150" src="images/students4.png">
<img height="150" src="images/students5.png">
<img height="150" src="images/students6.png">
'''

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Lives impacted"
      icon = "icon-check"
      from = 0
      to = 3213496886
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Innovation awards received"
      icon = "icon-trophy"
      from = 0
      to = 26
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy employees"
      icon = "icon-emotsmile"
      from = 0
      to = 12945
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Articles published by our researchers"
      icon = "icon-docs"
      from = 0
      to = 163472
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    title = "Apply now!"
    description = '''
Join the MarvFamily right now!

The **Robotics Branch**, together with the **Software and Microcoding Branch** is now hiring software engineers with degrees in either Computer Science or Computer Engineering to a special position as a Robot Tester. Applicants to the position of Robot Tester must state so in their applications and apply using the below link.

**<a href="https://marvellous.itch.io/marvellous-inc">Apply now!</a>**

<img height="50" src="images/steam.png">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<img height="50" src="images/humble.png">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<a href="https://marvellous.itch.io/marvellous-inc"><img height="50" src="images/itch.png"></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<img height="50" src="images/gog.png">
'''

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; <a href="https://marvelloussoft.github.io">MarvellousSoft</a>'
